### ISSUE TITLE
No release to Gitlab package registry

### ISSUE THREAD

**Issue by silvio-gratani** [ambimax/semantic-release-composer#15]
Using v1.0.0

When used alongside `@semantic-release/gitlab` in a GitLab project only the release is created while no artifact is generated in the package registry.

Gitlab docs on [installing a Composer package](https://docs.gitlab.com/ee/user/packages/composer_repository/#install-a-composer-package) states that "A package in the Package Registry" is required.

Is it a bug o it has not been meant to work on Gitlab?

**Comment by christian98** [comment]
Yes, we had the same problem. We solved it by running a `deploy` job only on tags:
```yml
deploy:
  stage: deploy
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=$CI_COMMIT_TAG "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'
  only:
    - tags
```

This should create the package in the Gitlab registry as well.
